language: php

php:
  - 5.6
  - 7.4
  - 8.0

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/coverage

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
